// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type _binding_ interface {
	Bind(*gin.Context) error
}

type _render_ interface {
	Render(*gin.Context)
}

type _default_ interface {
	Bind(*gin.Context, any) error
	BindJson(*gin.Context, any) error
	Render(*gin.Context, any, error)
}

type Admin interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	AdminUserDelete(*web.AdminUserDeleteReq) error
	AdminUserRoleLogs(*web.AdminUserRoleLogsReq) (*web.AdminUserRoleLogsResp, error)
	AdminUserRoleChange(*web.AdminUserRoleReq) error
	AdminUserDetail(*web.AdminUserDetailReq) (*web.AdminUserDetailResp, error)
	AdminUserList(*web.AdminUserListReq) (*web.AdminUserListResp, error)
	SaveSettings(*web.AdminSettingsSaveReq) (*web.AdminSettingsSaveResp, error)
	GetSettingsValues() (*web.AdminSettingsValuesResp, error)
	GetSettingsSchema() (*web.AdminSettingsSchemaResp, error)
	UpdateSiteSettings(*web.SiteSettingsReq) (*web.SiteSettingsResp, error)
	GetSiteSettings() (*web.SiteSettingsResp, error)
	SiteInfo(*web.SiteInfoReq) (*web.SiteInfoResp, error)
	ChangeUserStatus(*web.ChangeUserStatusReq) error

	mustEmbedUnimplementedAdminServant()
}

// RegisterAdminServant register Admin servant to gin
func RegisterAdminServant(e *gin.Engine, s Admin) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("POST", "admin/user/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminUserDeleteReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AdminUserDelete(req))
	})
	router.Handle("GET", "admin/user/role/logs", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminUserRoleLogsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.AdminUserRoleLogs(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/user/role", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminUserRoleReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AdminUserRoleChange(req))
	})
	router.Handle("GET", "admin/user/detail", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminUserDetailReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.AdminUserDetail(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "admin/user/list", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminUserListReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.AdminUserList(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/settings/save", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminSettingsSaveReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.SaveSettings(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "admin/settings/values", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		resp, err := s.GetSettingsValues()
		s.Render(c, resp, err)
	})
	router.Handle("GET", "admin/settings/schema", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		resp, err := s.GetSettingsSchema()
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/site/profile", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.SiteSettingsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.UpdateSiteSettings(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "admin/site/profile", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}

		resp, err := s.GetSiteSettings()
		s.Render(c, resp, err)
	})
	router.Handle("GET", "admin/site/status", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.SiteInfoReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.SiteInfo(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/user/status", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.ChangeUserStatusReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.ChangeUserStatus(req))
	})
}

// UnimplementedAdminServant can be embedded to have forward compatible implementations.
type UnimplementedAdminServant struct{}

func (UnimplementedAdminServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedAdminServant) AdminUserDelete(req *web.AdminUserDeleteReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) AdminUserRoleLogs(req *web.AdminUserRoleLogsReq) (*web.AdminUserRoleLogsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) AdminUserRoleChange(req *web.AdminUserRoleReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) AdminUserDetail(req *web.AdminUserDetailReq) (*web.AdminUserDetailResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) AdminUserList(req *web.AdminUserListReq) (*web.AdminUserListResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) SaveSettings(req *web.AdminSettingsSaveReq) (*web.AdminSettingsSaveResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) GetSettingsValues() (*web.AdminSettingsValuesResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) GetSettingsSchema() (*web.AdminSettingsSchemaResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) UpdateSiteSettings(req *web.SiteSettingsReq) (*web.SiteSettingsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) GetSiteSettings() (*web.SiteSettingsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) SiteInfo(req *web.SiteInfoReq) (*web.SiteInfoResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) ChangeUserStatus(req *web.ChangeUserStatusReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAdminServant) mustEmbedUnimplementedAdminServant() {}
