// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type Audit interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	ListAuditLogs(*web.AdminAuditLogsReq) (*web.AdminAuditLogsResp, error)
	AuditAvatarAction(*web.AdminAuditAvatarReq) error
	ListAuditAvatars(*web.AdminAuditAvatarsReq) (*web.AdminAuditAvatarsResp, error)
	AuditNicknameAction(*web.AdminAuditNicknameReq) error
	ListAuditNicknames(*web.AdminAuditNicknamesReq) (*web.AdminAuditNicknamesResp, error)
	AuditCommentAction(*web.AdminAuditCommentReq) error
	ListAuditComments(*web.AdminAuditCommentsReq) (*web.AdminAuditCommentsResp, error)
	AuditPostAction(*web.AdminAuditPostReq) error
	ListAuditPosts(*web.AdminAuditPostsReq) (*web.AdminAuditPostsResp, error)

	mustEmbedUnimplementedAuditServant()
}

// RegisterAuditServant register Audit servant to gin
func RegisterAuditServant(e *gin.Engine, s Audit) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("GET", "admin/audit/logs", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditLogsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditLogs(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/audit/avatar", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditAvatarReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AuditAvatarAction(req))
	})
	router.Handle("GET", "admin/audit/avatars", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditAvatarsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditAvatars(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/audit/nickname", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditNicknameReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AuditNicknameAction(req))
	})
	router.Handle("GET", "admin/audit/nicknames", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditNicknamesReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditNicknames(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/audit/comment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditCommentReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AuditCommentAction(req))
	})
	router.Handle("GET", "admin/audit/comments", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditCommentsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditComments(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/audit/post", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditPostReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AuditPostAction(req))
	})
	router.Handle("GET", "admin/audit/posts", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditPostsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditPosts(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedAuditServant can be embedded to have forward compatible implementations.
type UnimplementedAuditServant struct{}

func (UnimplementedAuditServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedAuditServant) ListAuditLogs(req *web.AdminAuditLogsReq) (*web.AdminAuditLogsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) AuditAvatarAction(req *web.AdminAuditAvatarReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) ListAuditAvatars(req *web.AdminAuditAvatarsReq) (*web.AdminAuditAvatarsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) AuditNicknameAction(req *web.AdminAuditNicknameReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) ListAuditNicknames(req *web.AdminAuditNicknamesReq) (*web.AdminAuditNicknamesResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) AuditCommentAction(req *web.AdminAuditCommentReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) ListAuditComments(req *web.AdminAuditCommentsReq) (*web.AdminAuditCommentsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) AuditPostAction(req *web.AdminAuditPostReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) ListAuditPosts(req *web.AdminAuditPostsReq) (*web.AdminAuditPostsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) mustEmbedUnimplementedAuditServant() {}
