// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type Audit interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	ListAuditLogs(*web.AdminAuditLogsReq) (*web.AdminAuditLogsResp, error)
	AuditPostAction(*web.AdminAuditPostReq) error
	ListAuditPosts(*web.AdminAuditPostsReq) (*web.AdminAuditPostsResp, error)

	mustEmbedUnimplementedAuditServant()
}

// RegisterAuditServant register Audit servant to gin
func RegisterAuditServant(e *gin.Engine, s Audit) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("GET", "admin/audit/logs", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditLogsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditLogs(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/audit/post", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditPostReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.AuditPostAction(req))
	})
	router.Handle("GET", "admin/audit/posts", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.AdminAuditPostsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.ListAuditPosts(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedAuditServant can be embedded to have forward compatible implementations.
type UnimplementedAuditServant struct{}

func (UnimplementedAuditServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedAuditServant) ListAuditLogs(req *web.AdminAuditLogsReq) (*web.AdminAuditLogsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) AuditPostAction(req *web.AdminAuditPostReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) ListAuditPosts(req *web.AdminAuditPostsReq) (*web.AdminAuditPostsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedAuditServant) mustEmbedUnimplementedAuditServant() {}
