// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type Chat interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	SendChatMessage(*web.SendChatMessageReq) (*web.SendChatMessageResp, error)
	GetChatHistory(*web.GetChatHistoryReq) (*web.GetChatHistoryResp, error)
	GetChatContacts(*web.GetChatContactsReq) (*web.GetChatContactsResp, error)

	mustEmbedUnimplementedChatServant()
}

// RegisterChatServant register Chat servant to gin
func RegisterChatServant(e *gin.Engine, s Chat) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("POST", "user/chat/send", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.SendChatMessageReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.SendChatMessage(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "user/chat/history", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.GetChatHistoryReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.GetChatHistory(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "user/chat/contacts", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.GetChatContactsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.GetChatContacts(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedChatServant can be embedded to have forward compatible implementations.
type UnimplementedChatServant struct{}

func (UnimplementedChatServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedChatServant) SendChatMessage(req *web.SendChatMessageReq) (*web.SendChatMessageResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedChatServant) GetChatHistory(req *web.GetChatHistoryReq) (*web.GetChatHistoryResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedChatServant) GetChatContacts(req *web.GetChatContactsReq) (*web.GetChatContactsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedChatServant) mustEmbedUnimplementedChatServant() {}
