// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type CourseLoose interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	CoursePlay(*web.CoursePlayReq) (*web.CoursePlayResp, error)
	CourseVideo(*web.CourseVideoReq) (*web.CourseVideoResp, error)
	CourseComments(*web.CourseCommentsReq) (*web.CourseCommentsResp, error)
	CourseDetail(*web.CourseDetailReq) (*web.CourseDetailResp, error)
	CourseList(*web.CourseListReq) (*web.CourseListResp, error)
	CourseGroups(*web.CourseGroupsReq) (*web.CourseGroupsResp, error)

	mustEmbedUnimplementedCourseLooseServant()
}

// RegisterCourseLooseServant register CourseLoose servant to gin
func RegisterCourseLooseServant(e *gin.Engine, s CourseLoose) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("POST", "course/play", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CoursePlayReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CoursePlay(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "course/video", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseVideoReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseVideo(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "course/comments", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseCommentsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseComments(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "course", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseDetailReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseDetail(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "course/list", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseListReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseList(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "course/groups", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseGroupsReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseGroups(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedCourseLooseServant can be embedded to have forward compatible implementations.
type UnimplementedCourseLooseServant struct{}

func (UnimplementedCourseLooseServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedCourseLooseServant) CoursePlay(req *web.CoursePlayReq) (*web.CoursePlayResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseLooseServant) CourseVideo(req *web.CourseVideoReq) (*web.CourseVideoResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseLooseServant) CourseComments(req *web.CourseCommentsReq) (*web.CourseCommentsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseLooseServant) CourseDetail(req *web.CourseDetailReq) (*web.CourseDetailResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseLooseServant) CourseList(req *web.CourseListReq) (*web.CourseListResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseLooseServant) CourseGroups(req *web.CourseGroupsReq) (*web.CourseGroupsResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseLooseServant) mustEmbedUnimplementedCourseLooseServant() {}
