// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/dao/jinzhu/dbr"
	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type CourseAdmin interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	UploadCourseVideo(*web.UploadCourseVideoReq) (*web.UploadCourseVideoResp, error)
	CourseUploadCredential(*web.CourseUploadCredentialReq) (*web.CourseUploadCredentialResp, error)
	DeleteCourse(*web.DeleteCourseReq) error
	UpdateCourse(*web.UpdateCourseReq) error
	CreateCourse(*web.CreateCourseReq) (*dbr.CourseFormated, error)
	DeleteCourseGroup(*web.DeleteCourseGroupReq) error
	UpdateCourseGroup(*web.UpdateCourseGroupReq) error
	CreateCourseGroup(*web.CourseGroupReq) (*dbr.CourseGroupFormated, error)

	mustEmbedUnimplementedCourseAdminServant()
}

// RegisterCourseAdminServant register CourseAdmin servant to gin
func RegisterCourseAdminServant(e *gin.Engine, s CourseAdmin) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("POST", "admin/course/video", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UploadCourseVideoReq)
		var bv _binding_ = req
		if err := bv.Bind(c); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.UploadCourseVideo(req)
		s.Render(c, resp, err)
	})
	router.Handle("GET", "admin/course/upload-credential", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseUploadCredentialReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseUploadCredential(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourse(req))
	})
	router.Handle("POST", "admin/course/update", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UpdateCourseReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.UpdateCourse(req))
	})
	router.Handle("POST", "admin/course", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CreateCourseReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourse(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/group/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseGroupReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourseGroup(req))
	})
	router.Handle("POST", "admin/course/group/update", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UpdateCourseGroupReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.UpdateCourseGroup(req))
	})
	router.Handle("POST", "admin/course/group", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseGroupReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourseGroup(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedCourseAdminServant can be embedded to have forward compatible implementations.
type UnimplementedCourseAdminServant struct{}

func (UnimplementedCourseAdminServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedCourseAdminServant) UploadCourseVideo(req *web.UploadCourseVideoReq) (*web.UploadCourseVideoResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CourseUploadCredential(req *web.CourseUploadCredentialReq) (*web.CourseUploadCredentialResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) DeleteCourse(req *web.DeleteCourseReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) UpdateCourse(req *web.UpdateCourseReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CreateCourse(req *web.CreateCourseReq) (*dbr.CourseFormated, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) DeleteCourseGroup(req *web.DeleteCourseGroupReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) UpdateCourseGroup(req *web.UpdateCourseGroupReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CreateCourseGroup(req *web.CourseGroupReq) (*dbr.CourseGroupFormated, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) mustEmbedUnimplementedCourseAdminServant() {}
