// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/dao/jinzhu/dbr"
	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type CourseAdmin interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	CourseUploadComplete(*web.CourseUploadCompleteReq) (*web.CourseUploadCompleteResp, error)
	CourseUploadInit(*web.CourseUploadInitReq) (*web.CourseUploadInitResp, error)
	DeleteCourseLesson(*web.DeleteCourseLessonReq) error
	UpdateCourseLesson(*web.UpdateCourseLessonReq) (*dbr.CourseLesson, error)
	CreateCourseLesson(*web.CourseLessonReq) (*dbr.CourseLesson, error)
	DeleteCourse(*web.DeleteCourseReq) error
	UpdateCourse(*web.UpdateCourseReq) error
	CreateCourse(*web.CreateCourseReq) (*dbr.CourseFormated, error)
	DeleteCourseGroup(*web.DeleteCourseGroupReq) error
	UpdateCourseGroup(*web.UpdateCourseGroupReq) error
	CreateCourseGroup(*web.CourseGroupReq) (*dbr.CourseGroupFormated, error)

	mustEmbedUnimplementedCourseAdminServant()
}

// RegisterCourseAdminServant register CourseAdmin servant to gin
func RegisterCourseAdminServant(e *gin.Engine, s CourseAdmin) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("POST", "admin/course/upload/complete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseUploadCompleteReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseUploadComplete(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/upload/init", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseUploadInitReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CourseUploadInit(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/lesson/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseLessonReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourseLesson(req))
	})
	router.Handle("POST", "admin/course/lesson/update", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UpdateCourseLessonReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.UpdateCourseLesson(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/lesson", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseLessonReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourseLesson(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourse(req))
	})
	router.Handle("POST", "admin/course/update", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UpdateCourseReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.UpdateCourse(req))
	})
	router.Handle("POST", "admin/course", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CreateCourseReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourse(req)
		s.Render(c, resp, err)
	})
	router.Handle("POST", "admin/course/group/delete", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseGroupReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourseGroup(req))
	})
	router.Handle("POST", "admin/course/group/update", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.UpdateCourseGroupReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.UpdateCourseGroup(req))
	})
	router.Handle("POST", "admin/course/group", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CourseGroupReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourseGroup(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedCourseAdminServant can be embedded to have forward compatible implementations.
type UnimplementedCourseAdminServant struct{}

func (UnimplementedCourseAdminServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedCourseAdminServant) CourseUploadComplete(req *web.CourseUploadCompleteReq) (*web.CourseUploadCompleteResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CourseUploadInit(req *web.CourseUploadInitReq) (*web.CourseUploadInitResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) DeleteCourseLesson(req *web.DeleteCourseLessonReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) UpdateCourseLesson(req *web.UpdateCourseLessonReq) (*dbr.CourseLesson, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CreateCourseLesson(req *web.CourseLessonReq) (*dbr.CourseLesson, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) DeleteCourse(req *web.DeleteCourseReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) UpdateCourse(req *web.UpdateCourseReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CreateCourse(req *web.CreateCourseReq) (*dbr.CourseFormated, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) DeleteCourseGroup(req *web.DeleteCourseGroupReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) UpdateCourseGroup(req *web.UpdateCourseGroupReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) CreateCourseGroup(req *web.CourseGroupReq) (*dbr.CourseGroupFormated, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCourseAdminServant) mustEmbedUnimplementedCourseAdminServant() {}
