// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/dao/jinzhu/dbr"
	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type CoursePriv interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	DeleteCourseCommentReply(*web.DeleteCourseCommentReplyReq) error
	CreateCourseCommentReply(*web.CreateCourseCommentReplyReq) (*dbr.CourseCommentReplyFormated, error)
	DeleteCourseComment(*web.DeleteCourseCommentReq) error
	CreateCourseComment(*web.CreateCourseCommentReq) (*dbr.CourseCommentFormated, error)

	mustEmbedUnimplementedCoursePrivServant()
}

// RegisterCoursePrivServant register CoursePriv servant to gin
func RegisterCoursePrivServant(e *gin.Engine, s CoursePriv) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("DELETE", "course/comment/reply", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseCommentReplyReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourseCommentReply(req))
	})
	router.Handle("POST", "course/comment/reply", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CreateCourseCommentReplyReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourseCommentReply(req)
		s.Render(c, resp, err)
	})
	router.Handle("DELETE", "course/comment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.DeleteCourseCommentReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		s.Render(c, nil, s.DeleteCourseComment(req))
	})
	router.Handle("POST", "course/comment", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.CreateCourseCommentReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.CreateCourseComment(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedCoursePrivServant can be embedded to have forward compatible implementations.
type UnimplementedCoursePrivServant struct{}

func (UnimplementedCoursePrivServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedCoursePrivServant) DeleteCourseCommentReply(req *web.DeleteCourseCommentReplyReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCoursePrivServant) CreateCourseCommentReply(req *web.CreateCourseCommentReplyReq) (*dbr.CourseCommentReplyFormated, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCoursePrivServant) DeleteCourseComment(req *web.DeleteCourseCommentReq) error {
	return mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCoursePrivServant) CreateCourseComment(req *web.CreateCourseCommentReq) (*dbr.CourseCommentFormated, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedCoursePrivServant) mustEmbedUnimplementedCoursePrivServant() {}
