// Code generated by go-mir. DO NOT EDIT.
// versions:
// - mir 5.3

package v1

import (
	"net/http"

	"github.com/BZYA-Community/WebsiteCore/internal/model/web"
	"github.com/alimy/mir/v5"
	"github.com/gin-gonic/gin"
)

type Identity interface {
	_default_

	// Chain provide handlers chain for gin
	Chain() gin.HandlersChain

	GetIdentity(*web.IdentityReq) (*web.IdentityResp, error)

	mustEmbedUnimplementedIdentityServant()
}

// RegisterIdentityServant register Identity servant to gin
func RegisterIdentityServant(e *gin.Engine, s Identity) {
	router := e.Group("v1")
	// use chain for router
	middlewares := s.Chain()
	router.Use(middlewares...)

	// register routes info to router
	router.Handle("GET", "identity", func(c *gin.Context) {
		select {
		case <-c.Request.Context().Done():
			return
		default:
		}
		req := new(web.IdentityReq)
		if err := s.Bind(c, req); err != nil {
			s.Render(c, nil, err)
			return
		}
		resp, err := s.GetIdentity(req)
		s.Render(c, resp, err)
	})
}

// UnimplementedIdentityServant can be embedded to have forward compatible implementations.
type UnimplementedIdentityServant struct{}

func (UnimplementedIdentityServant) Chain() gin.HandlersChain {
	return nil
}

func (UnimplementedIdentityServant) GetIdentity(req *web.IdentityReq) (*web.IdentityResp, error) {
	return nil, mir.Errorln(http.StatusNotImplemented, http.StatusText(http.StatusNotImplemented))
}

func (UnimplementedIdentityServant) mustEmbedUnimplementedIdentityServant() {}
