// Copyright 2023 ROC. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

package web

import (
	"github.com/BZYA-Community/WebsiteCore/pkg/xerror"
)

// nolint
var (
	ErrUsernameHasExisted      = xerror.NewError(20001, "用户名已存在")
	ErrUsernameLengthLimit     = xerror.NewError(20002, "用户名长度3~12")
	ErrUsernameCharLimit       = xerror.NewError(20003, "用户名只能包含字母、数字")
	ErrPasswordLengthLimit     = xerror.NewError(20004, "密码长度6~16")
	ErrUserRegisterFailed      = xerror.NewError(20005, "用户注册失败")
	ErrUserHasBeenBanned       = xerror.NewError(20006, "该账户已被封停")
	ErrNoPermission            = xerror.NewError(20007, "无权限执行该请求")
	ErrUserHasBindOTP          = xerror.NewError(20008, "当前用户已绑定二次验证")
	ErrUserOTPInvalid          = xerror.NewError(20009, "二次验证码验证失败")
	ErrUserNoBindOTP           = xerror.NewError(20010, "当前用户未绑定二次验证")
	ErrErrorOldPassword        = xerror.NewError(20011, "当前用户密码验证失败")
	ErrErrorCaptchaPassword    = xerror.NewError(20012, "图形验证码验证失败")
	ErrAccountNoPhoneBind      = xerror.NewError(20013, "拒绝操作: 账户未绑定手机号")
	ErrTooManyLoginError       = xerror.NewError(20014, "登录失败次数过多，请稍后再试")
	ErrGetPhoneCaptchaError    = xerror.NewError(20015, "短信验证码获取失败")
	ErrTooManyPhoneCaptchaSend = xerror.NewError(20016, "短信验证码获取次数已达今日上限")
	ErrExistedUserPhone        = xerror.NewError(20017, "该手机号已被绑定")
	ErrErrorPhoneCaptcha       = xerror.NewError(20018, "手机验证码不正确")
	ErrMaxPhoneCaptchaUseTimes = xerror.NewError(20019, "手机验证码已达最大使用次数")
	ErrNicknameLengthLimit     = xerror.NewError(20020, "昵称长度2~12")
	ErrNoExistUsername         = xerror.NewError(20021, "用户不存在")
	ErrNoAdminPermission       = xerror.NewError(20022, "无管理权限")
	ErrDisallowUserRegister    = xerror.NewError(20023, "系统不允许注册用户")

	ErrGetPostsFailed          = xerror.NewError(30001, "获取动态列表失败")
	ErrCreatePostFailed        = xerror.NewError(30002, "动态发布失败")
	ErrGetPostFailed           = xerror.NewError(30003, "获取动态详情失败")
	ErrDeletePostFailed        = xerror.NewError(30004, "动态删除失败")
	ErrLockPostFailed          = xerror.NewError(30005, "动态锁定失败")
	ErrGetPostTagsFailed       = xerror.NewError(30006, "获取话题列表失败")
	ErrInvalidDownloadReq      = xerror.NewError(30007, "附件下载请求不合法")
	ErrDownloadReqError        = xerror.NewError(30008, "附件下载请求失败")
	ErrInsuffientDownloadMoney = xerror.NewError(30009, "附件下载失败:账户资金不足")
	ErrDownloadExecFail        = xerror.NewError(30010, "附件下载失败:扣费失败")
	ErrStickPostFailed         = xerror.NewError(30011, "动态置顶失败")
	ErrVisblePostFailed        = xerror.NewError(30012, "更新可见性失败")
	ErrHighlightPostFailed     = xerror.NewError(30013, "动态设为亮点失败")
	ErrGetPostsUnknowStyle     = xerror.NewError(30014, "使用未知样式参数获取动态列表")
	ErrGetPostsNilUser         = xerror.NewError(30015, "使用游客账户获取动态详情失败")
	ErrPostContentsEmpty       = xerror.NewError(30016, "内容不能为空")
	ErrPostContentsTooLong     = xerror.NewError(30017, "内容超过长度限制")

	ErrGetCommentsFailed      = xerror.NewError(40001, "获取评论列表失败")
	ErrCreateCommentFailed    = xerror.NewError(40002, "评论发布失败")
	ErrGetCommentFailed       = xerror.NewError(40003, "获取评论详情失败")
	ErrDeleteCommentFailed    = xerror.NewError(40004, "评论删除失败")
	ErrCreateReplyFailed      = xerror.NewError(40005, "评论回复失败")
	ErrGetReplyFailed         = xerror.NewError(40006, "获取评论详情失败")
	ErrMaxCommentCount        = xerror.NewError(40007, "评论数已达最大限制")
	ErrGetCommentThumbs       = xerror.NewError(40008, "获取评论点赞信息失败")
	ErrHighlightCommentFailed = xerror.NewError(40009, "设置精选评论失败")

	ErrGetMessagesFailed = xerror.NewError(50001, "获取消息列表失败")
	ErrReadMessageFailed = xerror.NewError(50002, "标记消息已读失败")
	ErrSendWhisperFailed = xerror.NewError(50003, "私信发送失败")
	ErrNoWhisperToSelf   = xerror.NewError(50004, "不允许给自己发送私信")
	ErrTooManyWhisperNum = xerror.NewError(50005, "今日私信次数已达上限")
	// ErrWhisperForbidden 身份组权限拒绝(details携带具体提示文案)
	ErrWhisperForbidden   = xerror.NewError(50006, "当前身份不支持该私信操作")
	ErrSystemChatReadonly = xerror.NewError(50007, "系统通知不支持回复")
	ErrDuplicateWhisper   = xerror.NewError(50008, "消息发送中, 请勿重复提交")
	// 私信权限具体拒绝原因(响应仅透传msg不透传details, 故每种原因独立错误码)
	ErrWhisperGuestNeedPhone = xerror.NewError(50009, "绑定手机号后才能发送私信")
	ErrWhisperOnePending     = xerror.NewError(50010, "对方回复你之前，只能发送一条私信")
	ErrWhisperPeerNoPhone    = xerror.NewError(50011, "对方还未绑定手机号，暂时无法接收私信")
	ErrWhisperBetweenDaoyou  = xerror.NewError(50012, "道友之间不能发送私信，可以通过加好友和关注互动")

	ErrGetCollectionsFailed = xerror.NewError(60001, "获取收藏列表失败")
	ErrGetStarsFailed       = xerror.NewError(60002, "获取点赞列表失败")

	ErrNoRequestingFriendToSelf   = xerror.NewError(80001, "不允许添加自己为好友")
	ErrNotExistFriendId           = xerror.NewError(80002, "好友id不存在")
	ErrSendRequestingFriendFailed = xerror.NewError(80003, "申请添加朋友请求发送失败")
	ErrAddFriendFailed            = xerror.NewError(80004, "添加好友失败")
	ErrRejectFriendFailed         = xerror.NewError(80005, "拒绝好友失败")
	ErrDeleteFriendFailed         = xerror.NewError(80006, "删除好友失败")
	ErrGetContactsFailed          = xerror.NewError(80007, "获取联系人列表失败")
	ErrNoActionToSelf             = xerror.NewError(80008, "不允许对自己操作")
	ErrFolloUserFailed            = xerror.NewError(80100, "关注失败")
	ErrUnfollowUserFailed         = xerror.NewError(80101, "取消关注失败")
	ErrListFollowsFailed          = xerror.NewError(80102, "获取关注列表失败")
	ErrListFollowingsFailed       = xerror.NewError(80103, "获取粉丝列表列表失败")
	ErrGetFollowCountFailed       = xerror.NewError(80104, "获取关注计数信息失败")
	ErrNotAllowFollowSelf         = xerror.NewError(80105, "不能关注自己")
	ErrNotAllowUnfollowSelf       = xerror.NewError(80106, "不能取消关注自己")

	ErrGetIndexTrendsFailed = xerror.NewError(802001, "获取动态条栏信息失败")

	ErrFollowTopicFailed      = xerror.NewError(90001, "关注话题失败")
	ErrUnfollowTopicFailed    = xerror.NewError(90002, "取消关注话题失败")
	ErrStickTopicFailed       = xerror.NewError(90003, "更行话题置顶状态失败")
	ErrPinTopicFailed         = xerror.NewError(90005, "更行话题钉住状态失败")
	ErrThumbsUpTweetComment   = xerror.NewError(90101, "评论点赞失败")
	ErrThumbsDownTweetComment = xerror.NewError(90102, "评论点踩失败")
	ErrThumbsUpTweetReply     = xerror.NewError(90103, "评论回复点赞失败")
	ErrThumbsDownTweetReply   = xerror.NewError(90104, "评论回复点踩失败")

	ErrFileUploadFailed = xerror.NewError(10200, "文件上传失败")
	ErrFileInvalidExt   = xerror.NewError(10201, "文件类型不合法")
	ErrFileInvalidSize  = xerror.NewError(10202, "文件大小超限")

	ErrRoleChangeFailed = xerror.NewError(11001, "角色变更失败")
	ErrAuditPostFailed  = xerror.NewError(11002, "审核操作失败")
	// 11003 运维保护: 非运维账号尝试变更运维相关角色 HTTP映射403
	ErrRoleChangeNoPermission = xerror.NewError(11003, "无权变更该用户角色")
	ErrUserDeleteFailed       = xerror.NewError(11004, "删除用户失败")
	ErrAuditCommentFailed     = xerror.NewError(11005, "评论审核操作失败")
	ErrAuditNicknameFailed    = xerror.NewError(11006, "昵称审核操作失败")

	ErrNotImplemented = xerror.NewError(10501, "功能未实现")
)
